version: '3.8'
services:
    php-apache-environment:
        container_name: php-apache
        build:
            context: ./php
            dockerfile: Dockerfile
        restart: always
        depends_on:
            - db
        volumes:
            - ./php/src:/var/www/html/
        ports:
            - 8000:80
    db:
        container_name: db
        image: db_image:version1
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: p4c1nt35@2022
            MYSQL_DATABASE: gestion_pacientes
            MYSQL_USER: admin
            MYSQL_PASSWORD: p4c1nt35@2022
        ports:
            - "9906:3306"
        volumes:
            - ./data/db:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - '8080:80'
        restart: always
        environment:
            PMA_HOST: db
        depends_on:
            - db